proxy: PORT=7980 npx judoscale-adapter-proxy-server

# NOTE: Enable either the `heroku_` processes or the `render_` processes based
# on which env you want to spoof locally.

heroku_spring: DYNO=web.1 ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-Dserver.port=8080"

# render_spring: RENDER_SERVICE_ID=srv-xyz RENDER_INSTANCE_ID=srv-xyz-1234 RENDER_SERVICE_TYPE=web ./mvnw spring-boot:run
